# .bashrc

alias vi=vim
alias cls=clear
# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

unset command_not_found_handle

ANDROID_SDK=/home/han/Android/Sdk/platform-tools
export PATH=$PATH:$ANDROID_SDK

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
